-- 1. CHAT MESSAGES TABLE
-- Stores every message from every user conversation.
CREATE TABLE
  chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users (id) ON DELETE CASCADE NOT NULL,
    -- A session_id groups a single conversation together.
    session_id UUID NOT NULL,
    -- 'user' or 'assistant'
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW ()
  );

-- 2. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

-- 3. CREATE SECURITY POLICY
-- Users can only see and create messages that belong to them.
CREATE POLICY "Users can manage their own chat messages." ON chat_messages
  FOR ALL USING (auth.uid () = user_id);