-- 1. SKILLS TABLE: Master list of all skills.
CREATE TABLE
  skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW ()
  );

-- 2. USER GOALS TABLE: Stores the primary goal for each user.
CREATE TABLE
  user_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users (id) ON DELETE CASCADE NOT NULL,
    goal_description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW ()
  );

-- 3. USER SKILLS TABLE: Links users to skills and their proficiency.
CREATE TABLE
  user_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users (id) ON DELETE CASCADE NOT NULL,
    skill_id BIGINT REFERENCES skills (id) ON DELETE CASCADE NOT NULL,
    proficiency SMALLINT NOT NULL DEFAULT 0 CHECK (
      proficiency >= 0
      AND proficiency <= 10
    ),
    UNIQUE (user_id, skill_id)
  );

-- 4. ROADMAP STEPS TABLE: Stores the generated roadmap steps for a user's goal.
CREATE TABLE
  roadmap_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users (id) ON DELETE CASCADE NOT NULL,
    goal_id BIGINT REFERENCES user_goals (id) ON DELETE CASCADE NOT NULL,
    step_number INT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    is_completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW ()
  );

-- 5. NOTIFICATIONS TABLE: Stores news, scholarships, fetched from an API.
CREATE TABLE
  notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    source_url TEXT UNIQUE, -- UNIQUE constraint prevents duplicate articles
    category TEXT,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW ()
  );

-- 6. ENABLE ROW LEVEL SECURITY (RLS) -- THIS IS CRITICAL FOR SECURITY
ALTER TABLE user_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE roadmap_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- 7. CREATE SECURITY POLICIES -- Define who can access what data
CREATE POLICY "Users can manage their own goals." ON user_goals FOR ALL USING (auth.uid () = user_id);
CREATE POLICY "Users can manage their own skills." ON user_skills FOR ALL USING (auth.uid () = user_id);
CREATE POLICY "Users can manage their own roadmaps." ON roadmap_steps FOR ALL USING (auth.uid () = user_id);
CREATE POLICY "Authenticated users can read notifications." ON notifications FOR SELECT USING (auth.role () = 'authenticated');